### ISSUE TITLE
Hi guys! I want to help with translation but I can't push my commit to repo

### ISSUE THREAD

**Issue by andrewincontact** [GitHowTo/githowto-content#59]
$ git push origin master
ERROR: Permission to GitHowTo/githowto-content.git denied to andrewincontact.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I did ssh-keygen on Windows and add ssh-code to github account. But I still can't push my commit.

My push command :  git push origin master

**Comment by neochief** [comment]
Hi Andrew!

Thank you for your help. I believe you have cloned this repository and tried to push the changes directly. This is not how it supposed to be done, because anyone would be able to mess with repositories. Here's how you suppose to contribute on Github:
1. Fork the repository of interest.
2. Clone the fork to your local machine.
3. Do all the work inside the cloned fork.
4. Once finished, create a pull request from your fork to the main repository.

You can find more information in Github manual:
https://help.github.com/en/articles/about-pull-requests

I'm closing this issue for now. Let me know if you have any questions.

**Comment by andrewincontact** [comment]
Thanks
